import { pool } from "./db.ts";
export type RppAttributionWindow = "12H" | "720H";
export type RppPerformanceFact = { date: string; itemCode: string; clicks: number; spend: number; sales12h: number; orders12h: number; sales720h: number; orders720h: number; sourceMtime?: string };
export type RppComparisonMetrics = { spend: number; clicks: number; sales: number; orders: number; averageCpc: number | null; cvr: number | null; roas: number | null };
const iso = (year:number,month:number,day:number) => `${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`;
function monthRange(month:string) { const [y,m]=month.split("-").map(Number); const end=new Date(Date.UTC(y,m,0)).getUTCDate(); return {startDate:iso(y,m,1),endDate:iso(y,m,end)}; }
function shiftMonth(month:string,delta:number) { const [y,m]=month.split("-").map(Number); const d=new Date(Date.UTC(y,m-1+delta,1)); return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`; }
export function aggregateRppFacts(rows:RppPerformanceFact[], attribution:RppAttributionWindow):RppComparisonMetrics { const spend=rows.reduce((s,r)=>s+r.spend,0),clicks=rows.reduce((s,r)=>s+r.clicks,0),sales=rows.reduce((s,r)=>s+(attribution==="12H"?r.sales12h:r.sales720h),0),orders=rows.reduce((s,r)=>s+(attribution==="12H"?r.orders12h:r.orders720h),0); return {spend,clicks,sales,orders,averageCpc:clicks?spend/clicks:null,cvr:clicks?orders/clicks*100:null,roas:spend?sales/spend*100:null}; }
function delta(a:number|null,b:number|null){return {absolute:a==null||b==null?null:a-b,percent:a==null||b==null||b===0?null:(a-b)/b*100,baselineAvailable:b!=null&&b!==0};}
function datesBetween(start:string,end:string){const out:string[]=[];for(let d=new Date(`${start}T00:00:00Z`);d<=new Date(`${end}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+1))out.push(d.toISOString().slice(0,10));return out;}
export function compareRppFacts(rows:RppPerformanceFact[],a:{startDate:string;endDate:string},b:{startDate:string;endDate:string},attribution:RppAttributionWindow){const inRange=(r:RppPerformanceFact,p:typeof a)=>r.date>=p.startDate&&r.date<=p.endDate;const ar=rows.filter(r=>inRange(r,a)),br=rows.filter(r=>inRange(r,b)),am=aggregateRppFacts(ar,attribution),bm=aggregateRppFacts(br,attribution);const coverage=(p:typeof a,rs:RppPerformanceFact[])=>{const available=[...new Set(rs.map(r=>r.date))];const expected=datesBetween(p.startDate,p.endDate);return {startDate:p.startDate,endDate:p.endDate,expectedDays:expected.length,availableDays:available.length,missingDates:expected.filter(d=>!available.includes(d))};};return {periodA:{range:coverage(a,ar),metrics:am},periodB:{range:coverage(b,br),metrics:bm},deltas:{spend:delta(am.spend,bm.spend),clicks:delta(am.clicks,bm.clicks),sales:delta(am.sales,bm.sales),orders:delta(am.orders,bm.orders),averageCpc:delta(am.averageCpc,bm.averageCpc),roas:delta(am.roas,bm.roas)},comparisonAvailable:ar.length>0&&br.length>0,warnings:[...(ar.length?[]:["期間Aのデータがありません"]),...(br.length?[]:["比較期間のデータがありません"])]};}
export function resolveRppComparisonPeriods(params:URLSearchParams){const preset=params.get("preset")||"MONTH",month=params.get("month")||new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Tokyo"}).slice(0,7);if(preset==="CUSTOM")return {a:{startDate:params.get("aStart")||monthRange(month).startDate,endDate:params.get("aEnd")||monthRange(month).endDate},b:{startDate:params.get("bStart")||monthRange(shiftMonth(month,-1)).startDate,endDate:params.get("bEnd")||monthRange(shiftMonth(month,-1)).endDate}};return {a:monthRange(month),b:monthRange(shiftMonth(month,preset==="YOY"?-12:-1))};}
export async function readRppDailySpendActuals(){if(!pool)return [];try{const result=await pool.query(`select performance_date::text as date,sum(spend)::text as spend from rpp_performance_daily where performance_date>=date_trunc('month',current_date)::date and performance_date<(date_trunc('month',current_date)+interval '1 month')::date group by performance_date order by performance_date`);return result.rows.map(row=>({date:row.date,spend:Number(row.spend)}));}catch(error){if((error as {code?:string}).code==="42P01")return [];throw error;}}

export async function readRppComparison(params:URLSearchParams){if(!pool)return {...compareRppFacts([],resolveRppComparisonPeriods(params).a,resolveRppComparisonPeriods(params).b,params.get("attribution")==="12H"?"12H":"720H"),attribution:params.get("attribution")==="12H"?"12H":"720H",source:"db:rpp_performance_daily"};const periods=resolveRppComparisonPeriods(params),item=params.get("itemCode")?.trim().toLowerCase()||"";let result;try{result=await pool.query(`select performance_date::text as date,item_code,clicks,spend,sales_12h,orders_12h,sales_720h,orders_720h,source_mtime from rpp_performance_daily where performance_date between $1 and $2 and ($3='' or item_code=$3) order by performance_date,item_code`,[periods.b.startDate<periods.a.startDate?periods.b.startDate:periods.a.startDate,periods.b.endDate>periods.a.endDate?periods.b.endDate:periods.a.endDate,item]);}catch(error){if((error as {code?:string}).code==="42P01")return {...compareRppFacts([],periods.a,periods.b,params.get("attribution")==="12H"?"12H":"720H"),attribution:params.get("attribution")==="12H"?"12H":"720H",source:"db:rpp_performance_daily"};throw error;}const rows=result.rows.map(r=>({date:r.date,itemCode:r.item_code,clicks:Number(r.clicks),spend:Number(r.spend),sales12h:Number(r.sales_12h),orders12h:Number(r.orders_12h),sales720h:Number(r.sales_720h),orders720h:Number(r.orders_720h),sourceMtime:new Date(r.source_mtime).toISOString()}));const attribution=params.get("attribution")==="12H"?"12H":"720H";return {...compareRppFacts(rows,periods.a,periods.b,attribution),attribution,source:"db:rpp_performance_daily"};}
