import { promises as fs } from "fs";
import path from "path";
import { pool } from "./db.ts";
import { appendRppAuditEvent } from "./rppAuditLog.ts";
export type RppAdGroup={name:string;targetRoas:number|null;itemCodes:string[]};
export type RppRoasSchedule={id:string;startsAt:string;endsAt:string;groupName:string;targetRoas:number;note:string;enabled:boolean;createdAt:string};
export type RppStrategySettings={groups:RppAdGroup[];schedules:RppRoasSchedule[];updatedAt:string|null};
export type RppRoasResolution={baseRoasFloor:number;effectiveRoasFloor:number;effectiveRoasSource:"SCHEDULE_GROUP"|"SCHEDULE_ALL"|"GROUP"|"TARGET";activeScheduleId:string|null;effectiveGroup:string};
const TABLE="rpp_strategy_settings",PROJECT_DIR=process.env.RPP_PROJECT_DIR??(process.platform==="darwin"?"/Users/nob/Projects/rpp-8am-notify":"/tmp/rpp-8am-notify"),FILE_PATH=path.join(PROJECT_DIR,"rpp_targets","rpp_strategy_settings.json"),DEFAULTS:RppStrategySettings={groups:[],schedules:[],updatedAt:null};
const text=(v:unknown)=>String(v??"").trim(),iso=(v:unknown)=>{const s=text(v);return s&&!Number.isNaN(new Date(s).getTime())?new Date(s).toISOString():"";};
export function normalizeRppStrategySettings(value:Partial<RppStrategySettings>={}):RppStrategySettings{const groups=Array.isArray(value.groups)?value.groups.map(row=>({name:text(row?.name),targetRoas:Number(row?.targetRoas)>=200&&Number(row?.targetRoas)<=5000?Math.round(Number(row.targetRoas)):null,itemCodes:[...new Set((Array.isArray(row?.itemCodes)?row.itemCodes:[]).map(c=>text(c).toLowerCase()).filter(Boolean))]})).filter(r=>r.name):[];const schedules=Array.isArray(value.schedules)?value.schedules.map(row=>({id:text(row?.id)||crypto.randomUUID(),startsAt:iso(row?.startsAt),endsAt:iso(row?.endsAt),groupName:text(row?.groupName),targetRoas:Math.round(Number(row?.targetRoas)||0),note:text(row?.note),enabled:row?.enabled!==false,createdAt:iso(row?.createdAt)||new Date().toISOString()})).filter(r=>r.startsAt&&r.endsAt&&r.startsAt<r.endsAt&&r.targetRoas>=200&&r.targetRoas<=5000):[];return{groups,schedules,updatedAt:typeof value.updatedAt==="string"?value.updatedAt:null};}
function validate(settings:RppStrategySettings){const names=settings.groups.map(g=>g.name);if(new Set(names).size!==names.length)throw new Error("広告グループ名が重複しています");for(const [i,a] of settings.schedules.entries())for(const b of settings.schedules.slice(i+1))if(a.enabled&&b.enabled&&a.groupName===b.groupName&&a.startsAt<b.endsAt&&b.startsAt<a.endsAt)throw new Error(`同一範囲の予約が重複しています: ${a.groupName||"全体"}`);}
async function ensureTable(){if(pool)await pool.query(`create table if not exists ${TABLE}(singleton boolean primary key default true check(singleton),payload jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now())`);}
export async function readRppStrategySettings(){if(pool){await ensureTable();const r=await pool.query(`select payload,updated_at from ${TABLE} where singleton=true`);if(r.rows[0])return{source:`db:${TABLE}`,settings:normalizeRppStrategySettings({...r.rows[0].payload,updatedAt:new Date(r.rows[0].updated_at).toISOString()})};}try{return{source:FILE_PATH,settings:normalizeRppStrategySettings(JSON.parse(await fs.readFile(FILE_PATH,"utf8")))}}catch{return{source:pool?`db:${TABLE}`:FILE_PATH,settings:DEFAULTS}}}
export async function writeRppStrategySettings(value:Partial<RppStrategySettings>,actorId="system"){const before=(await readRppStrategySettings()).settings,settings=normalizeRppStrategySettings({...value,updatedAt:new Date().toISOString()});validate(settings);if(pool){await ensureTable();await pool.query(`insert into ${TABLE}(singleton,payload,updated_at) values(true,$1::jsonb,now()) on conflict(singleton) do update set payload=$1::jsonb,updated_at=now()`,[JSON.stringify(settings)]);}else{await fs.mkdir(path.dirname(FILE_PATH),{recursive:true});await fs.writeFile(FILE_PATH,`${JSON.stringify(settings,null,2)}\n`);}await appendRppAuditEvent("STRATEGY_SETTINGS_UPDATED","RPP広告グループ/ROAS予約",{before,after:settings,productionChange:false},actorId);return readRppStrategySettings();}
export function resolveRppRoas(base:number,itemCode:string,adGroup:string,settings:RppStrategySettings,at=new Date()):RppRoasResolution{const group=settings.groups.find(g=>g.name===adGroup||g.itemCodes.includes(itemCode.toLowerCase())),now=at.toISOString();const active=settings.schedules.filter(s=>s.enabled&&s.startsAt<=now&&now<s.endsAt&&(s.groupName===""||s.groupName===(group?.name??adGroup)));const groupSchedule=active.filter(s=>s.groupName!=="").sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).at(-1),allSchedule=active.filter(s=>s.groupName==="").sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).at(-1),schedule=groupSchedule??allSchedule;if(schedule)return{baseRoasFloor:base,effectiveRoasFloor:schedule.targetRoas,effectiveRoasSource:groupSchedule?"SCHEDULE_GROUP":"SCHEDULE_ALL",activeScheduleId:schedule.id,effectiveGroup:group?.name??adGroup};if(group?.targetRoas)return{baseRoasFloor:base,effectiveRoasFloor:group.targetRoas,effectiveRoasSource:"GROUP",activeScheduleId:null,effectiveGroup:group.name};return{baseRoasFloor:base,effectiveRoasFloor:base,effectiveRoasSource:"TARGET",activeScheduleId:null,effectiveGroup:group?.name??adGroup};}
export function effectiveRoasForTarget(base:number,itemCode:string,adGroup:string,settings:RppStrategySettings,date?:Date){return resolveRppRoas(base,itemCode,adGroup,settings,date).effectiveRoasFloor;}
